### ISSUE TITLE
Lazy loading Portfolio Homepage

### ISSUE THREAD

**Issue by kellermatthis** [pyronaur/easy-photography-portfolio#12]
Hi,
first of all a big compliment to your plugin! I like it very much and it is easy to handle. I have one question though. Is it possible to implement Lazy Loading into the portfolio homepage and also display more than 100 entries?
Kind regards from Germany,
Matthis

**Comment by Fausztusz** [comment]
Hello,

I had the same problem and solved it with a bit of butcher work. Instead of lazyload I did pagination.

First at the `wp-content/plugins/photography-portfolio/Photography_Portfolio/Core/Query.php`

```php
public function increase_ppp_limit( \WP_Query $query ) {
        if ( $this->is_archive || $this->is_category ) {
                $query->set( 'numberposts', -1 );               //Removes the 100 limit
                $query->set( 'posts_per_page', get_option( 'posts_per_page' ) );
                $query->set( 'paged', get_query_var('page') );
        }
}
```

Then put the pagination links to the 'footer.php'. The portfolios per page can be set from the Settings/Reading

```php
 paginate_links([ 'mid_size'=> 3,
                          'end_size'=>1,
                       ])
```

**Comment by kellermatthis** [comment]
Hello, thank you very much for your answer. I still have two questions. I replaced your code in the Query.php. Now 10 galleries are displayed. Where can I change that? I can't find the setting.

The pagination link code is included in the footer.php of the theme. Unfortunately no page numbers are displayed. Do I have to do more?
Thank you and many greetings,
Matthis

**Comment by Fausztusz** [comment]
Hello,

You can set the number of portfolios in the admin panel under
Settings/Reading/"Blog pages show at max"

To get the pagination links you maybe have to use "echo paginate_links(...
)"
I had some extra code there and didnt check if the simple paginate_links is
correct.

Greetings
András


kellermatthis <notifications@github.com> ezt írta (időpont: 2019. ápr. 30.,
K 9:45):

**Comment by Fausztusz** [comment]
Another correction:

<?php echo paginate_links(...)>

András Fauszt <fauszt.andras19@gmail.com> ezt írta (időpont: 2019. máj. 1.,
Sze 19:03):

**Comment by Fausztusz** [comment]
Hello, 
You can set the number of portfolios in the admin panel under Settings/Reading/"Blog pages show at max" 
To get the pagination links you maybe have to use 
```
<php? 
    echo paginate_links(... )
>```
I had some extra code there and didn't check if the simple paginate_links is correct.

**Comment by kellermatthis** [comment]
Hi, thanks again for your answer! 
I missed the echo. The navigation bar can now be seen on every page, but I will solve that with an if condition.
However, when I navigate to the next page in my portfolio now, /page/2 will be added to the URL, but the portfolio entries will not change. It's still the 15 most recent ones that were also displayed on the first page.
Do you know why?
Thank you and many greetings,
Matthis

**Comment by Fausztusz** [comment]
Hi,
I `diff`-ed both my theme and easy-photography-portfolio folders but did not found anyting relevant difference other then what I wrote above.
One little thing that my link after clicking to the pagination link is 
`mysite/index.php/page/2/`

Maybe you should try [this on stackoverflow](https://stackoverflow.com/a/21416153) or check out [this (very slow) video](https://www.youtube.com/watch?v=HMscydyViZw&t) I used this for my site.

**Comment by kellermatthis** [comment]
Hey, sorry for the late reply.
For me it was changing
$query->set( 'paged', get_query_var('page') );
to
$query->set( 'paged', get_query_var('paged') );
and it worked.
Thank you very much for your help!
Kind regards!
